# System
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias cc='clear'

# Golang executables
alias assetfinder='~/go/bin/assetfinder'
alias subfinder='~/go/bin/subfinder'
alias shuffledns='~/go/bin/shuffledns'
alias chaos='~/go/bin/chaos'
alias dalfox='~/go/bin/dalfox'
alias ffuf='~/go/bin/ffuf'
alias gau='~/go/bin/gau'
alias gf='~/go/bin/gf'
alias hakrawler='~/go/bin/hakrawler'
alias unfurl='~/go/bin/unfurl'
alias waybackurls='~/go/bin/waybackurls'
alias nuclei='~/go/bin/nuclei'
alias httprobe='~/go/bin/gau'
alias httpx='~/go/bin/gau'
alias anew='~/go/bin/anew'
alias notify='~/go/bin/notify'
alias intercept='~/go/bin/intercept'
